require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClocksController do

  # This should return the minimal set of attributes required to create a valid
  # Clock. As you add validations to Clock, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClocksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all clocks as @clocks" do
      clock = Clock.create! valid_attributes
      get :index, {}, valid_session
      assigns(:clocks).should eq([clock])
    end
  end

  describe "GET show" do
    it "assigns the requested clock as @clock" do
      clock = Clock.create! valid_attributes
      get :show, {:id => clock.to_param}, valid_session
      assigns(:clock).should eq(clock)
    end
  end

  describe "GET new" do
    it "assigns a new clock as @clock" do
      get :new, {}, valid_session
      assigns(:clock).should be_a_new(Clock)
    end
  end

  describe "GET edit" do
    it "assigns the requested clock as @clock" do
      clock = Clock.create! valid_attributes
      get :edit, {:id => clock.to_param}, valid_session
      assigns(:clock).should eq(clock)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Clock" do
        expect {
          post :create, {:clock => valid_attributes}, valid_session
        }.to change(Clock, :count).by(1)
      end

      it "assigns a newly created clock as @clock" do
        post :create, {:clock => valid_attributes}, valid_session
        assigns(:clock).should be_a(Clock)
        assigns(:clock).should be_persisted
      end

      it "redirects to the created clock" do
        post :create, {:clock => valid_attributes}, valid_session
        response.should redirect_to(Clock.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved clock as @clock" do
        # Trigger the behavior that occurs when invalid params are submitted
        Clock.any_instance.stub(:save).and_return(false)
        post :create, {:clock => { "user" => "invalid value" }}, valid_session
        assigns(:clock).should be_a_new(Clock)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Clock.any_instance.stub(:save).and_return(false)
        post :create, {:clock => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested clock" do
        clock = Clock.create! valid_attributes
        # Assuming there are no other clocks in the database, this
        # specifies that the Clock created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Clock.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => clock.to_param, :clock => { "user" => "" }}, valid_session
      end

      it "assigns the requested clock as @clock" do
        clock = Clock.create! valid_attributes
        put :update, {:id => clock.to_param, :clock => valid_attributes}, valid_session
        assigns(:clock).should eq(clock)
      end

      it "redirects to the clock" do
        clock = Clock.create! valid_attributes
        put :update, {:id => clock.to_param, :clock => valid_attributes}, valid_session
        response.should redirect_to(clock)
      end
    end

    describe "with invalid params" do
      it "assigns the clock as @clock" do
        clock = Clock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Clock.any_instance.stub(:save).and_return(false)
        put :update, {:id => clock.to_param, :clock => { "user" => "invalid value" }}, valid_session
        assigns(:clock).should eq(clock)
      end

      it "re-renders the 'edit' template" do
        clock = Clock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Clock.any_instance.stub(:save).and_return(false)
        put :update, {:id => clock.to_param, :clock => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested clock" do
      clock = Clock.create! valid_attributes
      expect {
        delete :destroy, {:id => clock.to_param}, valid_session
      }.to change(Clock, :count).by(-1)
    end

    it "redirects to the clocks list" do
      clock = Clock.create! valid_attributes
      delete :destroy, {:id => clock.to_param}, valid_session
      response.should redirect_to(clocks_url)
    end
  end

end
